; Super teste integrado - Software Básico
TAM EQU 4
FLAG EQU 1

SECTION TEXT
IF FLAG
    INPUT VETOR+0
    LOAD VETOR+0
    DIV DOIS
    STORE VETOR+1
    MULT DOIS
    STORE VETOR+2
    LOAD VETOR+0
    SUB VETOR+2
    STORE VETOR+3
    OUTPUT VETOR+3
    COPY VETOR+1,VETOR+0
    LOAD VETOR+0
    JMPP L1
    STOP

L1:
    LOAD VETOR+0
    DIV DOIS
    STORE VETOR+1
    MULT DOIS
    STORE VETOR+2
    LOAD VETOR+0
    SUB VETOR+2
    STORE VETOR+3
    OUTPUT VETOR+3
    COPY VETOR+1,VETOR+0
    LOAD VETOR+0
    JMPP L1
    STOP

SECTION DATA
DOIS: CONST 2
VETOR: SPACE TAM
